### ISSUE TITLE
Setting minimum / maximum values

### ISSUE THREAD

**Issue by eclewlow** [bradhowes/Knob#2]
Using Swift / Mac OS build:

If a value > 1.0 (e.g. `10`) is provided for `maximum` to the KnobView constructor, the resulting knob will behave erratically when mouse-dragged on.

https://github.com/bradhowes/Knob/blob/03cc5441521a618559bd6b83ae597264aac51651/Sources/Knob-macOS/KnobView.swift#L40-L45

![output](https://user-images.githubusercontent.com/32854625/217442507-7c2c12b5-61f2-487b-b969-1641ed43e7d2.gif)

**Comment by eclewlow** [comment]
Added this code to my fork

https://github.com/bradhowes/Knob/commit/215e819b894493a0d24b61968e908bd473aad1e4

It fixes the knob indicator erratic movement, but there's something wrong with the value printing.  Will look into it later.

**Comment by eclewlow** [comment]
The previous fix didn't account for negative `minimum` values, which is a different issue.

This code seems to fix both issues.

https://github.com/bradhowes/Knob/commit/87739233800cff3ac57e06b7daa1f013293aa3eb

**Comment by eclewlow** [comment]
Oh.. I see you have a helper variable for this exact situation.  `angleForValue`

https://github.com/bradhowes/Knob/commit/b6266823beb51fbf5f7afe453b7177f30321686a

**Comment by bradhowes** [comment]
Thanks @eclewlow for the issue! I pushed an update with a fix. I was usually thinking in normalized coordinate space, so I made modifications to stay there, but report out values in user coordinates using the minimumValue and maximumValue settings.
