### ISSUE TITLE
Logarithmic scale

### ISSUE THREAD

**Issue by eclewlow** [bradhowes/Knob#3]
It would be nice to have a logarithmic scale option.

I'm working on an audio application that has a low pass filter, and a cutoff parameter ranging in the audible range (20Hz to 20kHz), and it's common for this parameter to have a knob that has more precision in the lower frequencies, and less precision in the higher frequencies.

I already wrote some code for doing the logarithmic scale on my own knob code, but I much prefer the look of this knob.  Maybe it would be easy to integrate.

https://github.com/eclewlow/Instrument/blob/main/InstrumentExtension/UI/KnobView2.swift

**Comment by bradhowes** [comment]
Hi @eclewlow, indeed that would be a great addition. I actually use the Knob class as a control for AUParameter editing in my own AUv3 components, but I have the transformation done in separate bit of [code](https://github.com/bradhowes/AUv3Support/blob/main/Sources/AUv3Support/Editors/FloatParameterEditor.swift#L193#L213) that only knows of a RangedControl protocol, which Knob then conforms to in my AUv3 components. It does expect that Knob is configured to work in the normalized space of 0-1.

Not sure why I did not pursue adapting Knob to host the log transformations, but I think it was to not clutter an already-large API. That and the fact that there is a discontinuity using log with certain min/max configurations which I did not want to try and contend with.
