### ISSUE TITLE
Hangs on macOS

### ISSUE THREAD

**Issue by ryanfrancesconi** [bradhowes/Knob#4]
hi,
I was trying out your class on macOS and noticed that it is causing an infinite display loop on:
`public func display(_ layer: CALayer) {`

if you remove the needsDisplay there it will fix it.
`needsDisplay = true`

I didn't try on iOS.

Thanks!
Ryan

(XCode 15.3, latest etc)

**Comment by bradhowes** [comment]
Hi Ryan, thanks for the report and the solution. Indeed, I reproduced what you found. I've pushed basically your change and fixed two tests that run on macOS. Seems to be ok now.

Brad
